#include "StatsMonitor.h"
#include "Fuzzer.h"
CHIP_ERROR fuzz::StatsMonitor::AddObservation(DeviceStateTracker && dsTracker, types::FuzzerObservation & observation)
{
    mObservationCounters[observation]++;
    // Delegate logging to the OutputLogger object.
    if (mObservationCounters[observation] == 1)
    {
        return fuzz::Fuzzer::GetInstance()->GetOutputLogger()->LogObservation(
            std::move(dsTracker), std::chrono::steady_clock::now(), observation.mCommand, observation.mCommandPath,
            observation.mStatusResponse, observation.mResponseData, &observation.mReportedData);
    }
    return CHIP_NO_ERROR;
}

void fuzz::StatsMonitor::TrackStatsFromContext(const FuzzerContext & context)
{
    if (context.commandPath.HasValue())
    {
        auto cmdPath = context.commandPath.Value();
        mTestcasesPerCommand[cmdPath]++;
        mErrorMapPerCommand[cmdPath][context.commandStatusResponse]++;
        mErrorCounters[context.commandStatusResponse]++;
        mCommandExecutionStats.push_back(context.executionStats);
    }
}

CHIP_ERROR fuzz::StatsMonitor::SaveData()
{
    return fuzz::Fuzzer::GetInstance()->GetOutputLogger()->LogStatistics(
        &mTestcasesPerCommand, &mErrorMapPerCommand, &mErrorCounters, &mCommandExecutionStats, &mSkippedTests, &mOrphanReports);
}

void fuzz::StatsMonitor::IncrementSubscriptionTimeouts(const chip::app::ConcreteCommandPath & path)
{
    mSubscriptionTimeouts[path]++;
    if (mSubscriptionTimeouts[path] >= kMaxSubscriptionTimeouts)
    {
        Fuzzer::GetInstance()->GetDeviceStateTracker()->WriteToCommandSpec(mDestination, path.mEndpointId, path.mClusterId,
                                                                           path.mCommandId, false);
    }
}

void fuzz::StatsMonitor::ResetSubscriptionTimeouts(const chip::app::ConcreteCommandPath & path)
{
    if (!Fuzzer::GetInstance()
             ->GetDeviceStateTracker()
             ->ReadCommandSpec(mDestination, path.mEndpointId, path.mClusterId, path.mCommandId)
             ->canGenerateReport)
    {
        ChipLogError(chipToolFuzzing,
                     "Reports were generated by command (0x%04" PRIX16 ", 0x%08" PRIX32 ", 0x%08" PRIX32
                     ") which was not expected to generate reports.",
                     path.mEndpointId, path.mClusterId, path.mCommandId);
    }
    mSubscriptionTimeouts[path] = 0U;
}
